### ISSUE TITLE
Integrar API de Geolocalização no Backend para Localização Atual

### ISSUE THREAD

**Issue by heitor-am** [ES2-UFPI/BoraJa#24]
## Descrição:
_Integrar API de geolocalização para obter a localização atual do usuário e do carro._

## Tarefas:

-  _Configurar a API no backend._
-  _Criar endpoints para obter a localização do usuário e do carro._
-  _Testar a integração da API._

**Comment by flavioaquino** [comment]
Finalizando issue, API coletando todas as localizações.
